minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@{{oxlintVersion}}'
  - '@oxlint/binding-android-arm64@{{oxlintVersion}}'
  - '@oxlint/binding-darwin-arm64@{{oxlintVersion}}'
  - '@oxlint/binding-darwin-x64@{{oxlintVersion}}'
  - '@oxlint/binding-freebsd-x64@{{oxlintVersion}}'
  - '@oxlint/binding-linux-arm-gnueabihf@{{oxlintVersion}}'
  - '@oxlint/binding-linux-arm-musleabihf@{{oxlintVersion}}'
  - '@oxlint/binding-linux-arm64-gnu@{{oxlintVersion}}'
  - '@oxlint/binding-linux-arm64-musl@{{oxlintVersion}}'
  - '@oxlint/binding-linux-ppc64-gnu@{{oxlintVersion}}'
  - '@oxlint/binding-linux-riscv64-gnu@{{oxlintVersion}}'
  - '@oxlint/binding-linux-riscv64-musl@{{oxlintVersion}}'
  - '@oxlint/binding-linux-s390x-gnu@{{oxlintVersion}}'
  - '@oxlint/binding-linux-x64-gnu@{{oxlintVersion}}'
  - '@oxlint/binding-linux-x64-musl@{{oxlintVersion}}'
  - '@oxlint/binding-openharmony-arm64@{{oxlintVersion}}'
  - '@oxlint/binding-win32-arm64-msvc@{{oxlintVersion}}'
  - '@oxlint/binding-win32-ia32-msvc@{{oxlintVersion}}'
  - '@oxlint/binding-win32-x64-msvc@{{oxlintVersion}}'
  - oxlint@{{oxlintVersion}}
  - '@oxfmt/binding-android-arm-eabi@{{oxfmtVersion}}'
  - '@oxfmt/binding-android-arm64@{{oxfmtVersion}}'
  - '@oxfmt/binding-darwin-arm64@{{oxfmtVersion}}'
  - '@oxfmt/binding-darwin-x64@{{oxfmtVersion}}'
  - '@oxfmt/binding-freebsd-x64@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-arm-gnueabihf@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-arm-musleabihf@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-arm64-gnu@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-arm64-musl@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-ppc64-gnu@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-riscv64-gnu@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-riscv64-musl@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-s390x-gnu@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-x64-gnu@{{oxfmtVersion}}'
  - '@oxfmt/binding-linux-x64-musl@{{oxfmtVersion}}'
  - '@oxfmt/binding-openharmony-arm64@{{oxfmtVersion}}'
  - '@oxfmt/binding-win32-arm64-msvc@{{oxfmtVersion}}'
  - '@oxfmt/binding-win32-ia32-msvc@{{oxfmtVersion}}'
  - '@oxfmt/binding-win32-x64-msvc@{{oxfmtVersion}}'
  - oxfmt@{{oxfmtVersion}}
  - '@smallmains/dev@{{devPackageVersion}}'
