import { defineConfig } from "oxlint";
import e18e from "./parts/e18e.js";
import ts from "./parts/ts.js";
import { cssExtGlob } from "./shared.js";

const base = defineConfig({
  plugins: ["eslint", "unicorn", "oxc", "import", "jsdoc", "promise", "typescript"],
  jsPlugins: ["./plugins/comments.js", "./plugins/consistent-esm-default-name.js"],
  options: {
    typeAware: true,
    reportUnusedDisableDirectives: "warn",
  },
  settings: {
    jsdoc: {
      tagNamePreference: {
        // oxlint-disable-next-line unicorn/no-useless-spread -- allowed tags.
        ...Object.fromEntries(
          [
            "reactive",
            "experimental",
            "decorator",
            "platform",
            "bin",
            "__NO_SIDE_EFFECTS__",
            "__PURE__",
          ].map(v => [v, v]),
        ),
      },
    },
  },
  categories: {
    correctness: "error",
  },
  rules: {
    "array-callback-return": "error",
    "block-scoped-var": "warn",
    "curly": ["warn", "multi-line"],
    "default-param-last": "warn",
    "eqeqeq": ["error", "always", { null: "ignore" }],
    "grouped-accessor-pairs": ["warn", "getBeforeSet"],
    "no-array-constructor": "error",
    "no-case-declarations": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": "warn",
    "no-empty": ["error", { allowEmptyCatch: true }],
    "no-extend-native": "error",
    "no-fallthrough": "error",
    "no-loop-func": "warn",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-promise-executor-return": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-return-assign": ["warn", "except-parens"],
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "warn",
    "no-template-curly-in-string": "warn",
    "no-throw-literal": "warn",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "warn",
    "no-unused-vars": [
      "error",
      {
        args: "all",
        argsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "no-useless-assignment": "warn",
    "no-useless-call": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-concat": "warn",
    "no-var": "warn",
    "prefer-const": ["warn", { destructuring: "any", ignoreReadBeforeAssign: true }],
    "prefer-object-has-own": "warn",
    "prefer-promise-reject-errors": "warn",
    "prefer-regex-literals": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "preserve-caught-error": "warn",
    "radix": "warn",

    "typescript/adjacent-overload-signatures": "warn",
    "typescript/ban-ts-comment": [
      "warn",
      {
        "ts-check": false,
        "ts-expect-error": "allow-with-description",
        "ts-ignore": true,
        "ts-nocheck": true,
        minimumDescriptionLength: 3,
      },
    ],
    "typescript/consistent-type-imports": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/non-nullable-type-assertion-style": "warn",
    "typescript/prefer-optional-chain": "warn",
    "typescript/no-empty-object-type": "warn",
    "typescript/no-deprecated": "warn",
    "typescript/promise-function-async": "warn",
    "typescript/require-await": "warn",
    "typescript/return-await": ["warn", "error-handling-correctness-only"],
    "typescript/strict-void-return": "warn",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-invalid-void-type": [
      "error",
      { allowAsThisParameter: true, allowInGenericTypeArguments: true },
    ],
    "typescript/switch-exhaustiveness-check": [
      "warn",
      { considerDefaultExhaustiveForUnions: true, requireDefaultForNonUnion: true },
    ],
    "typescript/unified-signatures": "warn",
    "typescript/no-misused-promises": "warn",
    "typescript/no-mixed-enums": "warn",
    "typescript/no-non-null-asserted-nullish-coalescing": "warn",
    "typescript/no-unnecessary-boolean-literal-compare": "warn",
    "typescript/no-unnecessary-condition": "warn",
    "typescript/no-unnecessary-template-expression": "warn",
    "typescript/no-unnecessary-type-arguments": "warn",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-unnecessary-type-conversion": "warn",
    "typescript/no-unnecessary-type-parameters": "warn",
    "typescript/no-unsafe-enum-comparison": "warn",
    "typescript/no-unsafe-function-type": "warn",
    "typescript/only-throw-error": [
      "warn",
      { allowThrowingAny: false, allowThrowingUnknown: false },
    ],
    "typescript/prefer-find": "warn",
    "typescript/prefer-for-of": "warn",
    "typescript/prefer-includes": "warn",
    "typescript/prefer-nullish-coalescing": "warn",
    "typescript/prefer-promise-reject-errors": "warn",
    "typescript/prefer-reduce-type-parameter": "warn",
    "typescript/prefer-return-this-type": "warn",
    "typescript/prefer-ts-expect-error": "warn",
    "typescript/related-getter-setter-pairs": "warn",
    "typescript/restrict-plus-operands": [
      "warn",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: true,
        allowRegExp: false,
      },
    ],
    "typescript/use-unknown-in-catch-callback-variable": "warn",

    "unicorn/escape-case": "warn",
    "unicorn/prefer-modern-math-apis": "warn",
    "unicorn/prefer-at": "warn",
    "unicorn/prefer-prototype-methods": "warn",
    "unicorn/prefer-structured-clone": "warn",
    "unicorn/switch-case-braces": ["warn", "always"],
    "unicorn/switch-case-break-position": "warn",
    "unicorn/prefer-negative-index": "warn",
    "unicorn/consistent-empty-array-spread": "warn",
    "unicorn/custom-error-definition": "warn",
    "unicorn/error-message": "warn",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-instanceof-array": "warn",
    "unicorn/no-instanceof-builtins": "warn",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-unnecessary-array-flat-depth": "warn",
    "unicorn/no-unnecessary-array-splice-count": "warn",
    "unicorn/no-unnecessary-slice-end": "warn",
    "unicorn/no-useless-collection-argument": "warn",
    "unicorn/no-useless-error-capture-stack-trace": "warn",
    "unicorn/no-useless-promise-resolve-reject": "warn",
    "unicorn/no-useless-switch-case": "warn",
    "unicorn/prefer-add-event-listener": "warn",
    "unicorn/prefer-array-find": "warn",
    "unicorn/prefer-array-flat-map": "warn",
    "unicorn/prefer-array-some": "warn",
    "unicorn/prefer-bigint-literals": "warn",
    "unicorn/prefer-date-now": "warn",
    "unicorn/prefer-dom-node-text-content": "warn",
    "unicorn/prefer-export-from": "warn",
    "unicorn/prefer-global-this": "warn",
    "unicorn/prefer-includes": "warn",
    "unicorn/prefer-keyboard-event-key": "warn",
    "unicorn/prefer-math-trunc": "warn",
    "unicorn/prefer-node-protocol": "warn",
    "unicorn/prefer-number-properties": "warn",
    "unicorn/prefer-object-from-entries": "warn",
    "unicorn/prefer-optional-catch-binding": "warn",
    "unicorn/prefer-regexp-test": "warn",
    "unicorn/prefer-single-call": "warn",
    "unicorn/prefer-spread": "warn",
    "unicorn/prefer-string-replace-all": "warn",
    "unicorn/prefer-string-slice": "warn",
    "unicorn/prefer-string-trim-start-end": "warn",
    "unicorn/require-array-join-separator": "warn",
    "unicorn/require-module-specifiers": "warn",
    "unicorn/require-number-to-fixed-digits-argument": "warn",
    "unicorn/require-post-message-target-origin": "warn",
    "unicorn/text-encoding-identifier-case": "warn",
    "unicorn/throw-new-error": "warn",

    "oxc/approx-constant": "warn",
    "oxc/bad-bitwise-operator": "warn",
    "oxc/misrefactored-assign-op": "error",
    "oxc/no-accumulating-spread": "warn",

    "promise/always-return": ["warn", { ignoreLastCallback: true }],
    "promise/catch-or-return": ["warn", { allowFinally: true }],
    "promise/no-multiple-resolved": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "warn",
    "promise/prefer-catch": "warn",

    "import/export": "error",
    "import/named": "error",
    "import/no-absolute-path": "warn",
    "import/no-cycle": ["warn", { ignoreTypes: true, allowUnsafeDynamicCyclicDependency: true }],
    "import/no-duplicates": "warn",
    "import/no-empty-named-blocks": "warn",
    "import/no-mutable-exports": "warn",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "import/no-self-import": "error",
    "import/no-unassigned-import": ["warn", { allow: [`**/*.${cssExtGlob}`] }],
    "import/no-webpack-loader-syntax": "warn",

    "comments/require-description": "error",

    "consistent-esm-default-name/default-import-name": "warn",
    "consistent-esm-default-name/default-export-name": "warn",

    "jsdoc/check-access": "error",
    "jsdoc/check-tag-names": ["warn", { typed: true }],
    "jsdoc/empty-tags": "error",

    "jsdoc/require-param-name": "warn",
    "jsdoc/require-throws-description": "warn",
    "jsdoc/require-yields-description": "warn",
  },
});

export default defineConfig({
  extends: [base, e18e, ts],
});

export { default as react } from "./parts/react.js";
export { default as vitest } from "./parts/vitest.js";
export { default as nodejs } from "./parts/nodejs.js";
export { default as security } from "./parts/security.js";
